
import { GoogleGenAI } from "@google/genai";
import { AspectRatio } from '../types';

if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const generateExpertPrompt = async (userPrompt: string): Promise<string> => {
    const metaPrompt = `
        You are the Sovereign Scribe, an expert AI Art Director's assistant. Your task is to translate a user's simple idea into a rich, detailed, and evocative prompt for an AI image generator.

        **Instructions:**
        1.  Take the user's simple narrative script.
        2.  Enrich it with "Magic Words": descriptive adjectives, artistic styles (e.g., photorealistic, hyperdetailed, cinematic, Unreal Engine 5 render, concept art), lighting descriptions (e.g., dramatic volumetric lighting, god rays), and composition details.
        3.  Add context like "trending on Artstation" or "award-winning photography" to enhance quality.
        4.  Based on the user's script, infer the best style. If it contains keywords like 'cinematic,' 'movie still,' or 'landscape,' lean into that style. If it contains 'portrait' or 'headshot,' focus on character details.

        Your final output must be ONLY the expert-level prompt as a single, continuous string. Do not add any conversational text, explanations, or markdown formatting.

        **User's Script:** "${userPrompt}"
    `;

    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: metaPrompt,
        });
        return response.text.trim();
    } catch (error) {
        console.error("Error generating expert prompt:", error);
        throw new Error("Failed to craft the expert prompt. Please try again.");
    }
};

export const generateImage = async (expertPrompt: string, aspectRatio: AspectRatio): Promise<string> => {
    try {
        const response = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: expertPrompt,
            config: {
                numberOfImages: 1,
                outputMimeType: 'image/jpeg',
                aspectRatio: aspectRatio,
            },
        });
        
        if (response.generatedImages && response.generatedImages.length > 0) {
            return response.generatedImages[0].image.imageBytes;
        } else {
            throw new Error("No image was generated by the API.");
        }
    } catch (error) {
        console.error("Error generating image:", error);
        throw new Error("Failed to generate the masterpiece. The digital canvas is resisting.");
    }
};
